backend:
  image:
    repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/japan/backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2

frontend:
  image:
    repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/japan/frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2

ingress:
  host: devops-project.local  # or your real domain if you have one

aws:
  region: us-east-1

serviceAccount:
  name: backend-sa
  roleArn: "arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/my-devops-project-backend-irsa"