apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }} # Took from values.yaml
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # Host port
      targetPort: 5000 # Port forwarding 
  type: ClusterIP # Default service