apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: mongo-uri
      remoteRef:
        key: my-devops-project/mongo-uri
        property: mongo-uri