apiVersion: v1        # Kubernetes API version
kind: ServiceAccount  # Creates a ServiceAccount resource

metadata:
  name: {{ .Values.serviceAccount.name }} # ServiceAccount name taken from values.yaml

  namespace: {{ .Values.namespace }} # Namespace taken from values.yaml

  {{- if .Values.serviceAccount.roleArn }} # Only add the annotation if roleArn is defined and not empty

  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }} # AWS IRSA annotation - links this ServiceAccount to an IAM Role

  {{- end }} # If roleArn is empty, the entire annotations block is skipped